# Generated by Django 5.0.3 on 2024-05-04 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('text', models.TextField(verbose_name='')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
